language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

gemfile:
  - Gemfile

script: "bundle exec rake spec"

notifications:
  irc: "irc.freenode.org#coap"
